const BUS = {
  CAN_BE_SAVED_FILTERS_CHANGE: "canBeSavedFiltersChange",
  TIME_INFO_CHANGE: "timeInfoChange",
  AGG_CHANGE: "aggChange",
  SEARCH_CHANGE: "searchChange",
  CHECKED_FIELDS_CHANGE: "checkedFieldsChange",
  COLUMNS_CHANGE: "columnsChange",
  COLUMNS_RESET: "columnsReset",
  TOTAL_CHANGING: "totalChanging",
  TOTAL_CHANGED: "totalChanged",
  EXPORT_CSV: "exportCSV",
  WANT_TO_DISPOSE: "wantToDispose",
  GIVE_YOU_CHECKED_LIST: "giveYouCheckedList",
  DRAG_TABLE: "dragTable",
  RECYCLE_RESTORE: "recycleRestore",
  RECYCLE_DELETE: "recycleDelete",
};

const FIELD_WIDTH_MAP = {
  anomaly_type: 170,
  participator: 160,
  from_zone: 170,
  from_datasource: 170,
  watchlists: 160,
  risk_score: 140,
  model_name: 110,
  start_time: 170,
  end_time: 170,
  found_time: 170,
  anomaly_desc: 280,
  summary: 280,
  wathclist: 160,
  account_state: 110,
  anomaly_count: 110,
  threat_count: 110,
  account_type: 170,
  device_type: 170,
  device_state: 110,
  app_type: 170,
  data_type: 170,
  threat_type: 170,
  threat_desc: 280,
  survey_opinion: 280,
  name: 130,
  watchlist: 160,
  resource: 110,
  status: 110,
  type: 170,
  survey_time: 170,
  survey_account: 140,
  survey_status: 110,
  survey_result: 110,
  // 应用
  app_name: 130,
  dept_name: 130,
  app_network_domain: 150,
  app_owner: 160,
  app_vendor: 160,
  app_value: 170,
  app_ip: 150,
  app_port: 110,
  app_url: 280,
  id: 170,
  // 用户
  person_name: 130,
  account: 130,
  person_email: 150,
  person_identity_card: 170,
  person_mobile: 170,
  person_office_phone: 170,
  person_status: 110,
  person_station: 140,
  person_location: 280,
  last_login_time: 170,
  // 设备
  device_name: 130,
  device_resource: 110,
  device_owner: 110,
  device_network_domain: 150,
  device_vendor: 160,
  device_value: 170,
  // 数据
  data_name: 130,
  data_owner: 160,
  data_table: 150,
  data_db: 140,
  data_ip: 150,
  data_value: 170,
  // 程序
  program_name: 130,
};

const FILTER_MODE = {
  MULTI_SELECT_1: "1",
  MULTI_SELECT_2: "2",
  MULTI_SELECT_3: "3",
  SCORE_SELECT: "4",
  NUMBER_SELECT: "5",
  TIME_SELECT: "6",
  SEARCH_SELECT: "7",
};

const PAGE_TYPE = {
  LIST_EXCEPTION: "list-exception",
  LIST_THREAT: "list-threat",
  LIST_USER: "list-user",
  LIST_DEVICE: "list-device",
  LIST_APPLICATION: "list-application",
  LIST_PROGRAM: "list-program",
  LIST_DATA: "list-data",

  OVERVIEW_EXCEPTION: "overview-exception",
  OVERVIEW_THREAT: "overview-threat",
  OVERVIEW_USER: "overview-user",
  OVERVIEW_DEVICE: "overview-device",
  OVERVIEW_APPLICATION: "overview-application",
  OVERVIEW_PROGRAM: "overview-program",
  OVERVIEW_DATA: "overview-data",
  OVERVIEW_ANALYSIS: "overview-analysis",
  OVERVIEW_HOME: "overview-home",

  DETAIL_EXCEPTION: "detail-exception",
  DETAIL_THREAT: "detail-threat",

  DETAIL_USER_GROUP: "detail-user-group",
  DETAIL_USER_THREAT: "detail-user-threat",
  DETAIL_USER_EXCEPTION: "detail-user-exception",

  DETAIL_DEVICE_GROUP: "detail-device-group",
  DETAIL_DEVICE_THREAT: "detail-device-threat",
  DETAIL_DEVICE_EXCEPTION: "detail-device-exception",

  DETAIL_APPLICATION_THREAT: "detail-application-threat",
  DETAIL_APPLICATION_EXCEPTION: "detail-application-exception",

  DETAIL_PROGRAM_THREAT: "detail-program-threat",
  DETAIL_PROGRAM_EXCEPTION: "detail-program-exception",

  DETAIL_DATA_THREAT: "detail-data-threat",
  DETAIL_DATA_EXCEPTION: "detail-data-exception",

  // 采集监控
  COLLECT_CONTROL: "collect-control",
  // 配置信息
  CONFIG_INFO: "config-info",
  // 数仓信息
  DATABASE_MANAGE: "database-manage",
  // 异常规则回收站
  RULE_RECYCLE_EXCEPTION: "rule-recycle-exception",
  // 慢SQL
  SLOW_SQL: "slow-sql",
};

const TIME = {
  DEFAULT_QUICK_TIME: "all", // 默认快捷时间
};

// 采集监控的搜索条件
const COLLECT_FILTER_TYPE = [
  {
    code: "collect",
    name: "采集监控",
    children: [
      {
        checked: false,
        code: "sourceName",
        filterMode: "7",
        name: "数据源",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "nodeId",
        filterMode: "7",
        name: "采集ID",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "flowType",
        filterMode: "7",
        name: "采集类型",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "assetNum",
        filterMode: "5",
        name: "资产数",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "weekNum",
        filterMode: "5",
        name: "近一周总数",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "weekSize",
        filterMode: "5",
        name: "近一周总容量",
        recoverData: null,
        sourceValue: "",
        status: null,
        unit: "G",
      },
      {
        checked: false,
        code: "dayNum",
        filterMode: "5",
        name: "当天总数",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "daySize",
        filterMode: "5",
        name: "当天总容量",
        recoverData: null,
        sourceValue: "",
        status: null,
        unit: "G",
      },
      {
        checked: false,
        code: "epm",
        filterMode: "5",
        name: "EPM",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
    ],
  },
];

// 配置信息的搜索条件
const CONFIG_INFO_FILTER_TYPE = [
  {
    code: "config-info",
    name: "配置信息",
    children: [
      {
        checked: false,
        code: "configName",
        filterMode: "7",
        name: "配置类型",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "backupFile",
        filterMode: "7",
        name: "备份文件",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "backupTime",
        filterMode: "6",
        name: "备份时间",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
    ],
  },
];

const DATABASE_MANAGE_FILTER_TYPE = [
  {
    code: "database-manage",
    name: "数仓信息",
    children: [
      {
        checked: false,
        code: "tableName",
        filterMode: "7",
        name: "表名",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "tableEngine",
        filterMode: "7",
        name: "表引擎类型",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "totalRows",
        filterMode: "5",
        leftMin: 0,
        rightMin: 0,
        name: "总数",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "totalCapacity",
        filterMode: "5",
        leftMin: 0,
        rightMin: 0,
        name: "容量",
        recoverData: null,
        sourceValue: "",
        status: null,
        unit: "G",
      },
    ],
  },
];

const SLOW_SQL_FILTER_TYPE = [
  {
    code: "slow-sql",
    name: "慢SQL",
    children: [
      {
        checked: false,
        code: "duration_avg",
        filterMode: "5",
        leftMin: 0,
        rightMin: 0,
        name: "duration_avg",
        recoverData: null,
        sourceValue: "",
        status: null,
        unit: "ms",
      },
      {
        checked: false,
        code: "duration_max",
        filterMode: "5",
        leftMin: 0,
        rightMin: 0,
        name: "duration_max",
        recoverData: null,
        sourceValue: "",
        status: null,
        unit: "ms",
      },
      {
        checked: false,
        code: "read_rows",
        filterMode: "5",
        leftMin: 0,
        rightMin: 0,
        name: "read_rows",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "read_bytes",
        filterMode: "5",
        leftMin: 0,
        rightMin: 0,
        name: "read_bytes",
        recoverData: null,
        sourceValue: "",
        status: null,
        unit: "B",
      },
      {
        checked: false,
        code: "written_rows",
        filterMode: "5",
        leftMin: 0,
        rightMin: 0,
        name: "written_rows",
        recoverData: null,
        sourceValue: "",
        status: null,
      },
      {
        checked: false,
        code: "written_bytes",
        filterMode: "5",
        leftMin: 0,
        rightMin: 0,
        name: "written_bytes",
        recoverData: null,
        sourceValue: "",
        status: null,
        unit: "B",
      },
    ],
  },
];

export {
  BUS,
  TIME,
  FIELD_WIDTH_MAP,
  FILTER_MODE,
  PAGE_TYPE,
  COLLECT_FILTER_TYPE,
  CONFIG_INFO_FILTER_TYPE,
  DATABASE_MANAGE_FILTER_TYPE,
  SLOW_SQL_FILTER_TYPE,
};
